### ISSUE TITLE
tests sporadically fail on windows 10x64

### ISSUE THREAD

**Issue by mayork** [convexengineering/SPaircraft#101]
Not sure what the issue is here. Seems about 1 in 5 to 1 in 7 pushes fail on the Windows 10 64 bit machine. I can't duplicate the behavior on my machine.

@bqpd @1ozturkbe

**Comment by bqpd** [comment]
It's the knife edge you're solving on...might be reduced by a lower constants relaxation, or an initial condition.

**Comment by mayork** [comment]
Are you sure about that? The model that is tested now has a lot less constants than the one that was tested on master. The currently tested model has also proved to be quite stable when I push it around...

**Comment by 1ozturkbe** [comment]
It's funny, because I'm running Win10x64, and I have never ever had that solve fail on me. It's definitely not a knife-edge solve.

**Comment by bqpd** [comment]
Hmm! @1ozturkbe, let's set aside 30m sometime to try and reproduce this on your machine

**Comment by 1ozturkbe** [comment]
Sounds good. Perhaps Thursday around our meeting with Bob?

**Comment by mayork** [comment]
@1ozturkbe my theory is it's mosek cli and signomial equalities see https://github.com/hoburg/turbofan/issues/8

**Comment by 1ozturkbe** [comment]
Hmm interesting and plausible hypothesis! @bqpd and I can dig into this.

**Comment by mayork** [comment]
closing. should be resolved by https://github.com/convexengineering/SPaircraft/commit/f7fc9f96bf75f486b8726e9aeb7d8841e2c47ac3 (not testing mosek_cli anymore_
