### ISSUE TITLE
migrate to convex engineering group?

### ISSUE THREAD

**Issue by mayork** [convexengineering/SPaircraft#103]
@bqpd @1ozturkbe can we somehow move this to where gpkit is now? Renaming could be easier but I'm not sure if that is possible.

Same question applies to the turbofan repo.

**Comment by mayork** [comment]
if we migrate these repos soon i can put the updated url in the engine paper which is about to be published (in the proofing phase)

**Comment by 1ozturkbe** [comment]
yesyesyes should be high on our list of priorities.

**Comment by bqpd** [comment]
what should our mit url be? convexengineering.mit.edu

**Comment by mayork** [comment]
@bqpd Sounds good to me

**Comment by 1ozturkbe** [comment]
We have migrated!! Closing! @mayork feel free to update the engine paper!

**Comment by mayork** [comment]
@1ozturkbe see https://github.com/hoburg/turbofan/issues/9
