### ISSUE TITLE
Nacelle height and diameter untight in LG for D8.2

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/SPaircraft#105]
Need to investigate...

**Comment by 1ozturkbe** [comment]
Interesting that the weights are still reasonable however.

**Comment by 1ozturkbe** [comment]
Hmmm has to do with no constraint on y_m, so y_m hits y_eng.
Problematic constraint:
```python
                    self.LG['d_{nacelle}']  + self.LG['h_{nacelle}'] <= self.LG['l_m'] + (self.VT['y_{eng}']-self.LG['y_m'])*self.LG['\\tan(\\gamma)'], # [SP]
```

**Comment by 1ozturkbe** [comment]
@bqpd it is interesting that the LHS of the constraint is 1e30, and the RHS is 0, but the constraint is still satisfied... any idea what is going on?

**Comment by mayork** [comment]
There's nothing to constrain nacelle height in this model. Nacelle is constrained in the LG.

**Comment by 1ozturkbe** [comment]
I know, but there is something funny mathematically...

**Comment by 1ozturkbe** [comment]
oh no, I totally thought that constraint was within a different boolean (rear_engine). I may be tripping here.

**Comment by 1ozturkbe** [comment]
This was totally silly of me... Closing.
