### ISSUE TITLE
change read-the-docs url

### ISSUE THREAD

**Issue by bqpd** [convexengineering/SPaircraft#108]
what about SPaircraft.rtfd.org ?

**Comment by 1ozturkbe** [comment]
I have tried, but I haven't been able to figure out how. If you know some references, can you let me know?

**Comment by bqpd** [comment]
I think you have to create a new one and copy the settings over :(((

**Comment by 1ozturkbe** [comment]
arrrggghh so painful. I was afraid that was going to be the answer...

**Comment by 1ozturkbe** [comment]
I fixed it!! Will fix in the project description as well.
