### ISSUE TITLE
why do tests take so long to run?

### ISSUE THREAD

**Issue by mayork** [convexengineering/SPaircraft#114]
All we are running is the optimal 737 case with just Mosek (not mosek_cli or cvxopt) which solves in tens of seconds...why does the build take 21 minutes? That's like 3.5 min per machine.

**Comment by mayork** [comment]
Is it running a lot of installs on each machine for each test or something?

**Comment by bqpd** [comment]
often it's the fact that it takes so long to get a slot on a windows machine. it's only ~5 minutes (https://acdl.mit.edu/csi/job/gpkit_ResearchModel_SPaircraft_Push/buildnode=windows10x64,optimizer=mosek/613/) after it gets a slot

**Comment by mayork** [comment]
Ahh that makes sense
