### ISSUE TITLE
Trying to remove some of the odd nuance...

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/SPaircraft#129]
I was just wondering what the reasoning was for [this](https://github.com/convexengineering/SPaircraft/blob/a73bdd7686d10eeae305486d53227505eb664e2e/aircraft.py#L1210).

**Comment by 1ozturkbe** [comment]
Let me know @mayork.

**Comment by mayork** [comment]
Looks like it’s setting a higher fan face Mach number for the large engine (I.e. less flow deceleration)

**Comment by 1ozturkbe** [comment]
Actually, I ended up clearing a ton of miscellaneous things that I was planning to post here. This is fine. Closing.
