### ISSUE TITLE
Make sweep a variable. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/SPaircraft#68]
This is a future improvement so that we don't have to keep subbing a wing sweep for different cruise speeds. Seems suboptimal. Would involve doing a fit of all of the trig functions around a reasonable sweep angle set (perhaps between 10 to 35 degrees?).

**Comment by bqpd** [comment]
(note that it's been easy since the last few versions to add:
constants that are a function of other constants
calculated variables that are a function of other variables)

**Comment by 1ozturkbe** [comment]
Thanks for the note @bqpd. Can you point to an example?

**Comment by bqpd** [comment]
http://gpkit.readthedocs.io/en/latest/advancedcommands.html#derived-variables

**Comment by 1ozturkbe** [comment]
I tried this using the approximations in gpkit.tools, in the sweepvar branch. Didn't work. Perhaps might resurrect in future, but unlikely.
