### ISSUE TITLE
Interesting HT behavior. 

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/SPaircraft#75]
Just wanted to post this as an issue, because I have not observed this behavior before, going from a M072 737 to a wing-engine D8. The discussion follows from the comments under commit  70e5e92d.

**Comment by 1ozturkbe** [comment]
Main observation: m_ratio higher in 737 (1.41 vs 1.11), which seems to help SM constraint satisfaction. This seems counter-intuitive, because lower AR tails have lower effectiveness, but higher m_ratio?

**Comment by 1ozturkbe** [comment]
Btw Martin, I am almost convinced that the m_{ratio} on the RHS of the equation should be a division, not a multiplication. Am I mistaken? Lmk. Might be significantly influencing our results.

**Comment by mayork** [comment]
i don't think so. I just checked and it aligns with Drela's boom flex write up

**Comment by mayork** [comment]
@1ozturkbe can you get VSP shots of optimal 737 w/fixed BPR at a min SM of 0.05 and 0.15? The behavior is not what I expect

**Comment by 1ozturkbe** [comment]
Saw Drela's email about the different SMs between the M0.8 and 0.72 aircraft (0.15 vs 0.05 respectively). Makes sense. I guess we should just change all of the subs to reflect this. I will post a VSP figure here for the 73s with the different SMs.

**Comment by mayork** [comment]
well run it first and look at what happens....unless i'm missing something the higher static margin made fuel burn better?

**Comment by 1ozturkbe** [comment]
I will post this incrementally. For a M0.8 73 with SM = 0.05, the Wf is 38700lbs. 
![m08737_sm05](https://cloud.githubusercontent.com/assets/15684191/26336619/235cc8e2-3f39-11e7-912b-d1cde9d1232f.png)

**Comment by 1ozturkbe** [comment]
For M0.8 737 with SM = 0.15, the fuel weight goes down to 35236lbs. Vht grows from 0.5 to 0.6
![m08737_sm15](https://cloud.githubusercontent.com/assets/15684191/26336743/cc926106-3f39-11e7-9945-2532acf1d3f8.png)

**Comment by 1ozturkbe** [comment]
So yes, a higher static margin makes the fuel burn better. Is this a weird finding? I'm not sure...

**Comment by 1ozturkbe** [comment]
I will generate the standard killer chart and its VSPs, and then analyse what is going on.

**Comment by 1ozturkbe** [comment]
I am having so much trouble actually generating these figures. Do you occasionally get UNKNOWNs in your solutions? This is killing me.

**Comment by 1ozturkbe** [comment]
Anyways, finally managed to generate new killer chart with the new SM. the results are... interesting...
[D8_standard_killer_chart.pdf](https://github.com/hoburg/d8/files/1020885/D8_standard_killer_chart.pdf)

**Comment by 1ozturkbe** [comment]
Slowing down now (and reducing the SM) actually increases fuel burn? Wowowow. The rest of the findings follow TASOPT/NASA roughly, other than the 2010 engines bit. what is the difference in this step @mayork?

**Comment by 1ozturkbe** [comment]
I am looking at the results now: 
TSFC: 0.62 -> 0.59
Pretty much identical fuselages, vertical tails, horizontal tails
L/D drop from 22.1 to 21.5, identical drags during the cruise phase. utterly puzzling why the L/D doesn't improve with the slowdown.

**Comment by 1ozturkbe** [comment]
Fuselage drag doesn't scale well... Fuselage drag 10% higher for the slower aircraft! Needs to be fixed.

**Comment by 1ozturkbe** [comment]
Why are the fuselage drag coefficients higher for the M072 D8 vs. the M08 D8, especially since we have the Mach scaling? I think something wonky is going on. But I have to get some sleep now.

**Comment by mayork** [comment]
Damn just realized I think I normalized the TASOPT value by Rfuse*Lfuse not Dfuse*Lfuse. Will check this morning.

**Comment by mayork** [comment]
As far as UNKOWN what environment are you running in?

**Comment by 1ozturkbe** [comment]
@mayork I still think the fuselage drag coefficient is the reason why we are getting a wonky result from slowing down. Why is the drag coefficient of the M0.72 737 16% higher than the drag coefficient of the M0.8 737? The higher drag results in only a 6% drag reduction for the fuselage for flying 10% slower, which would explain why we are getting a net penalty.

**Comment by 1ozturkbe** [comment]
It's still funny to me that as SMmin goes up from 0.05 to 0.15, the fuel weight goes down... I just replicated the results above for a second time.

**Comment by mayork** [comment]
@1ozturkbe is this still active or can it be closed?

**Comment by 1ozturkbe** [comment]
This issue needs to be addressed, still active.

**Comment by 1ozturkbe** [comment]
no longer able to replicate this. I'm not sure exactly why, but it seems well-behaved (tail grows, fuel weight increases). Closing.
