### ISSUE TITLE
require code reviews for pushes to master?

### ISSUE THREAD

**Issue by mayork** [convexengineering/SPaircraft#94]
is this something we should do now that we are closing things out with the models?

**Comment by 1ozturkbe** [comment]
Hmmm, good question. It is a good idea I think, although it will put a small slowdown in how fast we can update things. Let's try it, and if it seems to be an impediment we can change it back?

**Comment by mayork** [comment]
or maybe should we wait till we submit the draft of the paper?

**Comment by 1ozturkbe** [comment]
honestly, I think the place this would help most with is the paper... I don't want us to have continuously changing results as you pointed out yesterday. Perhaps we keep a branch that stays behind master then, and implement reviews later?

**Comment by mayork** [comment]
so you're saying branch something now called like 'paper draft'?

**Comment by 1ozturkbe** [comment]
yeah something like that. On a side note, I am starting to realize what a pain in the neck it is to include code with papers... you have to make sure that you don't change it post-submission so that your results can be replicated :P

**Comment by mayork** [comment]
yeah for the engine paper i just dropped all the code (my repo and gpkit) into dropbox right after submitting and saved the commit hashes i used...that's really all you can do

**Comment by 1ozturkbe** [comment]
I guess let's draw a line at commit  bb3ac2d  for the paper, and just keep updating master until we get the paper ready?

**Comment by mayork** [comment]
yeah that's fine with me...i'm going to write a small script that automates the multi-objective table so if there are no other updates to master before that we can bump the line up to include that on master. If not we can merge it later.

**Comment by 1ozturkbe** [comment]
K. When you are done with that script, you can post the final commit hash here.

**Comment by 1ozturkbe** [comment]
I think we have decided that it is a good idea. I would prefer to implement this somewhat informally, especially since the updates are likely just going to be in structure/documentation rather than actual modeling. @mayork if you agree please close.

**Comment by 1ozturkbe** [comment]
@mayork closing this. I think we can coordinate this informally.
